services:
  client_prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
  client_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Required for Vite to accept connections
      - VITE_HOST=0.0.0.0
      
      # Required for hot-reloading
      - CHOKIDAR_USEPOLLING=true